driverDatabase=org.postgresql.Driver
urlDatabase=jdbc:postgresql://localhost:5432/library_db
usernameDatabase=library
passwordDatabase=password

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.show_sql=true